import Head from "next/head";
import About from "../components/About";
import MyExpertise from "../components/MyExpertise";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 md:gap-20 ">
        <About />
        <MyExpertise />
      </div>
    </div>
  );
}
